### ISSUE TITLE
Asks for DEVKITARM despite not using it

### ISSUE THREAD

**Issue by aplumafreak500** [JimB16/SMS#1]
https://github.com/JimB16/SMS/blob/3a7e8b5c4ac9fd8826fcd014aac141e295b0a5ed/Makefile#L7-L9

Should be DEVKITPPC, not DEVKITARM

**Comment by JimB16** [comment]
You're right, that's a case of too much copy and paste. I will fix it.

**Comment by JimB16** [comment]
Removed DEVKITARM from the makefile and fixed some other minor things after I updated my DevKitPro version.
